### ISSUE TITLE
Don't check lib into source control

### ISSUE THREAD

**Issue by ashaffer** [MattMcFarland/sequelize-relay#1]
This project looks pretty cool. Just a small nitpick though, most people don't check their built files into version control. Might want to add `lib` to your gitignore.

**Comment by MattMcFarland** [comment]
Thanks, adding this as a todo!

**Comment by MattMcFarland** [comment]
Yep this is a bug

**Comment by MattMcFarland** [comment]
fixed in v0.0.5 - thanks again
