### ISSUE TITLE
Expose a method which will take a single SequelizeModel instance

### ISSUE THREAD

**Issue by ranjithnori** [MattMcFarland/sequelize-relay#57]
Exposing a pure function which will take a single SequelizeModel instance and return the dataValues object seems to be a useful helper method. I felt the need while doing a Relay mutation myself.

I can help you with a PR if you agree :)

**Comment by MattMcFarland** [comment]
I agree, feel free to send a PR! thanks :+1:

**Comment by MattMcFarland** [comment]
I was just looking into this, and the sequelizemodel instance should already have the .dataValues object on it.  Unless you can explain further?
