### ISSUE TITLE
Package on npmjs.com has no runnable contents.

### ISSUE THREAD

**Issue by dervos** [MattMcFarland/sequelize-relay#81]
When I install this package from npm I get the error: 

```Error: Cannot find module 'sequelize-relay'```

The installed package in my node_modules seems empty. Running it in the browser on npm also [fails](https://runkit.com/58402c705c4c7e0014a13cb3/58402c705c4c7e0014a13cb4).

It seems something went wrong while publishing the package to npm.

**Comment by MattMcFarland** [comment]
uh oh! Thanks for sharing I'll fix right away.

**Comment by MattMcFarland** [comment]
fixed! sorry about that :(
